server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: cards-dev
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
