server:
  port: 8085
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: cards-dev
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/random_fights
    username: admin
    password: yoink